language: cpp
sudo: true
compiler: gcc
install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8"; fi
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - boost-latest
        packages:
            - g++-4.8
            - cmake
before_install:
    - sudo add-apt-repository ppa:ubuntu-sdk-team/ppa -y
    - sudo apt-get update -qq
    - sudo apt-get install qt5-default qttools5-dev-tools
    - export QMAKE=/usr/lib/x86_64-linux-gnu/qt5/bin/qmake
    - sudo add-apt-repository ppa:kubuntu-ppa/backports -y
    - sudo apt-get update -qq
    - sudo apt-get install -qq cmake=2.8.12.2-0ubuntu1~ubuntu12.04.1~ppa2
    - sudo apt-get install libboost1.55-all-dev
before_script:
    - BUILD_DIR=`pwd`/Tools/CodeManager/build
    - mkdir -p ${BUILD_DIR}
    - cd ${BUILD_DIR}
    - wget http://github.com/zeux/pugixml/releases/download/v1.6/pugixml-1.6.tar.gz
    - tar xzfv pugixml-1.6.tar.gz
    - cd pugixml-1.6
    - cmake scripts
    - make
    - sudo make install
    - cd ${BUILD_DIR}
    - wget https://github.com/google/googletest/archive/master.zip
    - unzip master.zip
    - cd googletest-master/googletest
    - cmake .
    - make
    - sudo cp libgtest* /lib
    - sudo cp -r include/gtest /usr/include
    - cd ${BUILD_DIR}
    - rm -rf *
    - cmake -DCMAKE_BUILD_TYPE=Debug ${BUILD_DIR}/..
script:
    - cd ${BUILD_DIR}
    - make
    - cd ${BUILD_DIR}/Core/test && ./CodeManagerCoreTest 
